{
  "cells": [
    {
      "cell_type": "code",
      "execution_count": 1,
      "metadata": {
        "colab": {
          "base_uri": "https://localhost:8080/"
        },
        "id": "WFBc9lIgDq8C",
        "outputId": "ce1a29dd-dd7c-492b-a946-e5d5d86b9db5"
      },
      "outputs": [
        {
          "name": "stdout",
          "output_type": "stream",
          "text": [
            "Requirement already satisfied: pip in /usr/local/lib/python3.10/dist-packages (23.3.1)\n",
            "Collecting pip\n",
            "  Downloading pip-24.2-py3-none-any.whl.metadata (3.6 kB)\n",
            "Downloading pip-24.2-py3-none-any.whl (1.8 MB)\n",
            "\u001b[2K   \u001b[90m━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━\u001b[0m \u001b[32m1.8/1.8 MB\u001b[0m \u001b[31m31.9 MB/s\u001b[0m eta \u001b[36m0:00:00\u001b[0m \u001b[36m0:00:01\u001b[0m\n",
            "\u001b[?25hInstalling collected packages: pip\n",
            "  Attempting uninstall: pip\n",
            "    Found existing installation: pip 23.3.1\n",
            "    Uninstalling pip-23.3.1:\n",
            "      Successfully uninstalled pip-23.3.1\n",
            "Successfully installed pip-24.2\n",
            "\u001b[33mWARNING: Running pip as the 'root' user can result in broken permissions and conflicting behaviour with the system package manager. It is recommended to use a virtual environment instead: https://pip.pypa.io/warnings/venv\u001b[0m\u001b[33m\n",
            "\u001b[0mNote: you may need to restart the kernel to use updated packages.\n",
            "Cloning into 'bleurt'...\n",
            "remote: Enumerating objects: 134, done.\u001b[K\n",
            "remote: Counting objects: 100% (18/18), done.\u001b[K\n",
            "remote: Compressing objects: 100% (18/18), done.\u001b[K\n",
            "remote: Total 134 (delta 0), reused 17 (delta 0), pack-reused 116 (from 1)\u001b[K\n",
            "Receiving objects: 100% (134/134), 31.28 MiB | 48.82 MiB/s, done.\n",
            "Resolving deltas: 100% (49/49), done.\n",
            "Processing /root/bleurt\n",
            "  Preparing metadata (setup.py) ... \u001b[?25ldone\n",
            "\u001b[?25hCollecting pandas (from BLEURT==0.0.2)\n",
            "  Downloading pandas-2.2.3-cp310-cp310-manylinux_2_17_x86_64.manylinux2014_x86_64.whl.metadata (89 kB)\n",
            "Requirement already satisfied: numpy in /usr/local/lib/python3.10/dist-packages (from BLEURT==0.0.2) (1.26.2)\n",
            "Collecting scipy (from BLEURT==0.0.2)\n",
            "  Downloading scipy-1.14.1-cp310-cp310-manylinux_2_17_x86_64.manylinux2014_x86_64.whl.metadata (60 kB)\n",
            "Collecting tensorflow (from BLEURT==0.0.2)\n",
            "  Downloading tensorflow-2.17.0-cp310-cp310-manylinux_2_17_x86_64.manylinux2014_x86_64.whl.metadata (4.2 kB)\n",
            "Collecting tf-slim>=1.1 (from BLEURT==0.0.2)\n",
            "  Downloading tf_slim-1.1.0-py2.py3-none-any.whl.metadata (1.6 kB)\n",
            "Collecting sentencepiece (from BLEURT==0.0.2)\n",
            "  Downloading sentencepiece-0.2.0-cp310-cp310-manylinux_2_17_x86_64.manylinux2014_x86_64.whl.metadata (7.7 kB)\n",
            "Collecting absl-py>=0.2.2 (from tf-slim>=1.1->BLEURT==0.0.2)\n",
            "  Downloading absl_py-2.1.0-py3-none-any.whl.metadata (2.3 kB)\n",
            "Requirement already satisfied: python-dateutil>=2.8.2 in /usr/local/lib/python3.10/dist-packages (from pandas->BLEURT==0.0.2) (2.8.2)\n",
            "Collecting pytz>=2020.1 (from pandas->BLEURT==0.0.2)\n",
            "  Downloading pytz-2024.2-py2.py3-none-any.whl.metadata (22 kB)\n",
            "Collecting tzdata>=2022.7 (from pandas->BLEURT==0.0.2)\n",
            "  Downloading tzdata-2024.2-py2.py3-none-any.whl.metadata (1.4 kB)\n",
            "Collecting astunparse>=1.6.0 (from tensorflow->BLEURT==0.0.2)\n",
            "  Downloading astunparse-1.6.3-py2.py3-none-any.whl.metadata (4.4 kB)\n",
            "Collecting flatbuffers>=24.3.25 (from tensorflow->BLEURT==0.0.2)\n",
            "  Downloading flatbuffers-24.3.25-py2.py3-none-any.whl.metadata (850 bytes)\n",
            "Collecting gast!=0.5.0,!=0.5.1,!=0.5.2,>=0.2.1 (from tensorflow->BLEURT==0.0.2)\n",
            "  Downloading gast-0.6.0-py3-none-any.whl.metadata (1.3 kB)\n",
            "Collecting google-pasta>=0.1.1 (from tensorflow->BLEURT==0.0.2)\n",
            "  Downloading google_pasta-0.2.0-py3-none-any.whl.metadata (814 bytes)\n",
            "Collecting h5py>=3.10.0 (from tensorflow->BLEURT==0.0.2)\n",
            "  Downloading h5py-3.11.0-cp310-cp310-manylinux_2_17_x86_64.manylinux2014_x86_64.whl.metadata (2.5 kB)\n",
            "Collecting libclang>=13.0.0 (from tensorflow->BLEURT==0.0.2)\n",
            "  Downloading libclang-18.1.1-py2.py3-none-manylinux2010_x86_64.whl.metadata (5.2 kB)\n",
            "Collecting ml-dtypes<0.5.0,>=0.3.1 (from tensorflow->BLEURT==0.0.2)\n",
            "  Downloading ml_dtypes-0.4.1-cp310-cp310-manylinux_2_17_x86_64.manylinux2014_x86_64.whl.metadata (20 kB)\n",
            "Collecting opt-einsum>=2.3.2 (from tensorflow->BLEURT==0.0.2)\n",
            "  Downloading opt_einsum-3.3.0-py3-none-any.whl.metadata (6.5 kB)\n",
            "Requirement already satisfied: packaging in /usr/local/lib/python3.10/dist-packages (from tensorflow->BLEURT==0.0.2) (23.2)\n",
            "Collecting protobuf!=4.21.0,!=4.21.1,!=4.21.2,!=4.21.3,!=4.21.4,!=4.21.5,<5.0.0dev,>=3.20.3 (from tensorflow->BLEURT==0.0.2)\n",
            "  Downloading protobuf-4.25.5-cp37-abi3-manylinux2014_x86_64.whl.metadata (541 bytes)\n",
            "Requirement already satisfied: requests<3,>=2.21.0 in /usr/local/lib/python3.10/dist-packages (from tensorflow->BLEURT==0.0.2) (2.31.0)\n",
            "Requirement already satisfied: setuptools in /usr/local/lib/python3.10/dist-packages (from tensorflow->BLEURT==0.0.2) (69.0.2)\n",
            "Requirement already satisfied: six>=1.12.0 in /usr/lib/python3/dist-packages (from tensorflow->BLEURT==0.0.2) (1.16.0)\n",
            "Collecting termcolor>=1.1.0 (from tensorflow->BLEURT==0.0.2)\n",
            "  Downloading termcolor-2.4.0-py3-none-any.whl.metadata (6.1 kB)\n",
            "Requirement already satisfied: typing-extensions>=3.6.6 in /usr/local/lib/python3.10/dist-packages (from tensorflow->BLEURT==0.0.2) (4.8.0)\n",
            "Collecting wrapt>=1.11.0 (from tensorflow->BLEURT==0.0.2)\n",
            "  Downloading wrapt-1.16.0-cp310-cp310-manylinux_2_5_x86_64.manylinux1_x86_64.manylinux_2_17_x86_64.manylinux2014_x86_64.whl.metadata (6.6 kB)\n",
            "Collecting grpcio<2.0,>=1.24.3 (from tensorflow->BLEURT==0.0.2)\n",
            "  Downloading grpcio-1.66.1-cp310-cp310-manylinux_2_17_x86_64.manylinux2014_x86_64.whl.metadata (3.9 kB)\n",
            "Collecting tensorboard<2.18,>=2.17 (from tensorflow->BLEURT==0.0.2)\n",
            "  Downloading tensorboard-2.17.1-py3-none-any.whl.metadata (1.6 kB)\n",
            "Collecting keras>=3.2.0 (from tensorflow->BLEURT==0.0.2)\n",
            "  Downloading keras-3.5.0-py3-none-any.whl.metadata (5.8 kB)\n",
            "Collecting tensorflow-io-gcs-filesystem>=0.23.1 (from tensorflow->BLEURT==0.0.2)\n",
            "  Downloading tensorflow_io_gcs_filesystem-0.37.1-cp310-cp310-manylinux_2_17_x86_64.manylinux2014_x86_64.whl.metadata (14 kB)\n",
            "Requirement already satisfied: wheel<1.0,>=0.23.0 in /usr/local/lib/python3.10/dist-packages (from astunparse>=1.6.0->tensorflow->BLEURT==0.0.2) (0.42.0)\n",
            "Collecting rich (from keras>=3.2.0->tensorflow->BLEURT==0.0.2)\n",
            "  Downloading rich-13.8.1-py3-none-any.whl.metadata (18 kB)\n",
            "Collecting namex (from keras>=3.2.0->tensorflow->BLEURT==0.0.2)\n",
            "  Downloading namex-0.0.8-py3-none-any.whl.metadata (246 bytes)\n",
            "Collecting optree (from keras>=3.2.0->tensorflow->BLEURT==0.0.2)\n",
            "  Downloading optree-0.12.1-cp310-cp310-manylinux_2_17_x86_64.manylinux2014_x86_64.whl.metadata (47 kB)\n",
            "Requirement already satisfied: charset-normalizer<4,>=2 in /usr/local/lib/python3.10/dist-packages (from requests<3,>=2.21.0->tensorflow->BLEURT==0.0.2) (3.3.2)\n",
            "Requirement already satisfied: idna<4,>=2.5 in /usr/local/lib/python3.10/dist-packages (from requests<3,>=2.21.0->tensorflow->BLEURT==0.0.2) (3.6)\n",
            "Requirement already satisfied: urllib3<3,>=1.21.1 in /usr/local/lib/python3.10/dist-packages (from requests<3,>=2.21.0->tensorflow->BLEURT==0.0.2) (2.1.0)\n",
            "Requirement already satisfied: certifi>=2017.4.17 in /usr/local/lib/python3.10/dist-packages (from requests<3,>=2.21.0->tensorflow->BLEURT==0.0.2) (2023.11.17)\n",
            "Collecting markdown>=2.6.8 (from tensorboard<2.18,>=2.17->tensorflow->BLEURT==0.0.2)\n",
            "  Downloading Markdown-3.7-py3-none-any.whl.metadata (7.0 kB)\n",
            "Collecting tensorboard-data-server<0.8.0,>=0.7.0 (from tensorboard<2.18,>=2.17->tensorflow->BLEURT==0.0.2)\n",
            "  Downloading tensorboard_data_server-0.7.2-py3-none-manylinux_2_31_x86_64.whl.metadata (1.1 kB)\n",
            "Collecting werkzeug>=1.0.1 (from tensorboard<2.18,>=2.17->tensorflow->BLEURT==0.0.2)\n",
            "  Downloading werkzeug-3.0.4-py3-none-any.whl.metadata (3.7 kB)\n",
            "Requirement already satisfied: MarkupSafe>=2.1.1 in /usr/local/lib/python3.10/dist-packages (from werkzeug>=1.0.1->tensorboard<2.18,>=2.17->tensorflow->BLEURT==0.0.2) (2.1.3)\n",
            "Collecting markdown-it-py>=2.2.0 (from rich->keras>=3.2.0->tensorflow->BLEURT==0.0.2)\n",
            "  Downloading markdown_it_py-3.0.0-py3-none-any.whl.metadata (6.9 kB)\n",
            "Requirement already satisfied: pygments<3.0.0,>=2.13.0 in /usr/local/lib/python3.10/dist-packages (from rich->keras>=3.2.0->tensorflow->BLEURT==0.0.2) (2.17.2)\n",
            "Collecting mdurl~=0.1 (from markdown-it-py>=2.2.0->rich->keras>=3.2.0->tensorflow->BLEURT==0.0.2)\n",
            "  Downloading mdurl-0.1.2-py3-none-any.whl.metadata (1.6 kB)\n",
            "Downloading tf_slim-1.1.0-py2.py3-none-any.whl (352 kB)\n",
            "Downloading pandas-2.2.3-cp310-cp310-manylinux_2_17_x86_64.manylinux2014_x86_64.whl (13.1 MB)\n",
            "\u001b[2K   \u001b[90m━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━\u001b[0m \u001b[32m13.1/13.1 MB\u001b[0m \u001b[31m212.8 MB/s\u001b[0m eta \u001b[36m0:00:00\u001b[0m\n",
            "\u001b[?25hDownloading scipy-1.14.1-cp310-cp310-manylinux_2_17_x86_64.manylinux2014_x86_64.whl (41.2 MB)\n",
            "\u001b[2K   \u001b[90m━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━\u001b[0m \u001b[32m41.2/41.2 MB\u001b[0m \u001b[31m195.0 MB/s\u001b[0m eta \u001b[36m0:00:00\u001b[0m00:01\u001b[0m\n",
            "\u001b[?25hDownloading sentencepiece-0.2.0-cp310-cp310-manylinux_2_17_x86_64.manylinux2014_x86_64.whl (1.3 MB)\n",
            "\u001b[2K   \u001b[90m━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━\u001b[0m \u001b[32m1.3/1.3 MB\u001b[0m \u001b[31m155.1 MB/s\u001b[0m eta \u001b[36m0:00:00\u001b[0m\n",
            "\u001b[?25hDownloading tensorflow-2.17.0-cp310-cp310-manylinux_2_17_x86_64.manylinux2014_x86_64.whl (601.3 MB)\n",
            "\u001b[2K   \u001b[90m━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━\u001b[0m \u001b[32m601.3/601.3 MB\u001b[0m \u001b[31m113.5 MB/s\u001b[0m eta \u001b[36m0:00:00\u001b[0m00:01\u001b[0m00:01\u001b[0m\n",
            "\u001b[?25hDownloading absl_py-2.1.0-py3-none-any.whl (133 kB)\n",
            "Downloading astunparse-1.6.3-py2.py3-none-any.whl (12 kB)\n",
            "Downloading flatbuffers-24.3.25-py2.py3-none-any.whl (26 kB)\n",
            "Downloading gast-0.6.0-py3-none-any.whl (21 kB)\n",
            "Downloading google_pasta-0.2.0-py3-none-any.whl (57 kB)\n",
            "Downloading grpcio-1.66.1-cp310-cp310-manylinux_2_17_x86_64.manylinux2014_x86_64.whl (5.7 MB)\n",
            "\u001b[2K   \u001b[90m━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━\u001b[0m \u001b[32m5.7/5.7 MB\u001b[0m \u001b[31m226.3 MB/s\u001b[0m eta \u001b[36m0:00:00\u001b[0m\n",
            "\u001b[?25hDownloading h5py-3.11.0-cp310-cp310-manylinux_2_17_x86_64.manylinux2014_x86_64.whl (5.3 MB)\n",
            "\u001b[2K   \u001b[90m━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━\u001b[0m \u001b[32m5.3/5.3 MB\u001b[0m \u001b[31m161.1 MB/s\u001b[0m eta \u001b[36m0:00:00\u001b[0m\n",
            "\u001b[?25hDownloading keras-3.5.0-py3-none-any.whl (1.1 MB)\n",
            "\u001b[2K   \u001b[90m━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━\u001b[0m \u001b[32m1.1/1.1 MB\u001b[0m \u001b[31m110.4 MB/s\u001b[0m eta \u001b[36m0:00:00\u001b[0m\n",
            "\u001b[?25hDownloading libclang-18.1.1-py2.py3-none-manylinux2010_x86_64.whl (24.5 MB)\n",
            "\u001b[2K   \u001b[90m━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━\u001b[0m \u001b[32m24.5/24.5 MB\u001b[0m \u001b[31m201.7 MB/s\u001b[0m eta \u001b[36m0:00:00\u001b[0m\n",
            "\u001b[?25hDownloading ml_dtypes-0.4.1-cp310-cp310-manylinux_2_17_x86_64.manylinux2014_x86_64.whl (2.2 MB)\n",
            "\u001b[2K   \u001b[90m━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━\u001b[0m \u001b[32m2.2/2.2 MB\u001b[0m \u001b[31m205.8 MB/s\u001b[0m eta \u001b[36m0:00:00\u001b[0m\n",
            "\u001b[?25hDownloading opt_einsum-3.3.0-py3-none-any.whl (65 kB)\n",
            "Downloading protobuf-4.25.5-cp37-abi3-manylinux2014_x86_64.whl (294 kB)\n",
            "Downloading pytz-2024.2-py2.py3-none-any.whl (508 kB)\n",
            "Downloading tensorboard-2.17.1-py3-none-any.whl (5.5 MB)\n",
            "\u001b[2K   \u001b[90m━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━\u001b[0m \u001b[32m5.5/5.5 MB\u001b[0m \u001b[31m95.9 MB/s\u001b[0m eta \u001b[36m0:00:00\u001b[0m\n",
            "\u001b[?25hDownloading tensorflow_io_gcs_filesystem-0.37.1-cp310-cp310-manylinux_2_17_x86_64.manylinux2014_x86_64.whl (5.1 MB)\n",
            "\u001b[2K   \u001b[90m━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━\u001b[0m \u001b[32m5.1/5.1 MB\u001b[0m \u001b[31m195.5 MB/s\u001b[0m eta \u001b[36m0:00:00\u001b[0m\n",
            "\u001b[?25hDownloading termcolor-2.4.0-py3-none-any.whl (7.7 kB)\n",
            "Downloading tzdata-2024.2-py2.py3-none-any.whl (346 kB)\n",
            "Downloading wrapt-1.16.0-cp310-cp310-manylinux_2_5_x86_64.manylinux1_x86_64.manylinux_2_17_x86_64.manylinux2014_x86_64.whl (80 kB)\n",
            "Downloading Markdown-3.7-py3-none-any.whl (106 kB)\n",
            "Downloading tensorboard_data_server-0.7.2-py3-none-manylinux_2_31_x86_64.whl (6.6 MB)\n",
            "\u001b[2K   \u001b[90m━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━\u001b[0m \u001b[32m6.6/6.6 MB\u001b[0m \u001b[31m190.7 MB/s\u001b[0m eta \u001b[36m0:00:00\u001b[0m\n",
            "\u001b[?25hDownloading werkzeug-3.0.4-py3-none-any.whl (227 kB)\n",
            "Downloading namex-0.0.8-py3-none-any.whl (5.8 kB)\n",
            "Downloading optree-0.12.1-cp310-cp310-manylinux_2_17_x86_64.manylinux2014_x86_64.whl (347 kB)\n",
            "Downloading rich-13.8.1-py3-none-any.whl (241 kB)\n",
            "Downloading markdown_it_py-3.0.0-py3-none-any.whl (87 kB)\n",
            "Downloading mdurl-0.1.2-py3-none-any.whl (10.0 kB)\n",
            "Building wheels for collected packages: BLEURT\n",
            "  Building wheel for BLEURT (setup.py) ... \u001b[?25ldone\n",
            "\u001b[?25h  Created wheel for BLEURT: filename=BLEURT-0.0.2-py3-none-any.whl size=16456765 sha256=d4abc7c918a0046de110878e2da01458df057e0523f5dea84d7fefa8d7e73e31\n",
            "  Stored in directory: /tmp/pip-ephem-wheel-cache-7hbivvjm/wheels/3a/e3/2a/480d15ae2d134b68b728a252f88f00161673c2fed07ab0598d\n",
            "Successfully built BLEURT\n",
            "Installing collected packages: sentencepiece, pytz, namex, libclang, flatbuffers, wrapt, werkzeug, tzdata, termcolor, tensorflow-io-gcs-filesystem, tensorboard-data-server, scipy, protobuf, optree, opt-einsum, ml-dtypes, mdurl, markdown, h5py, grpcio, google-pasta, gast, astunparse, absl-py, tf-slim, tensorboard, pandas, markdown-it-py, rich, keras, tensorflow, BLEURT\n",
            "Successfully installed BLEURT-0.0.2 absl-py-2.1.0 astunparse-1.6.3 flatbuffers-24.3.25 gast-0.6.0 google-pasta-0.2.0 grpcio-1.66.1 h5py-3.11.0 keras-3.5.0 libclang-18.1.1 markdown-3.7 markdown-it-py-3.0.0 mdurl-0.1.2 ml-dtypes-0.4.1 namex-0.0.8 opt-einsum-3.3.0 optree-0.12.1 pandas-2.2.3 protobuf-4.25.5 pytz-2024.2 rich-13.8.1 scipy-1.14.1 sentencepiece-0.2.0 tensorboard-2.17.1 tensorboard-data-server-0.7.2 tensorflow-2.17.0 tensorflow-io-gcs-filesystem-0.37.1 termcolor-2.4.0 tf-slim-1.1.0 tzdata-2024.2 werkzeug-3.0.4 wrapt-1.16.0\n",
            "\u001b[33mWARNING: Running pip as the 'root' user can result in broken permissions and conflicting behaviour with the system package manager, possibly rendering your system unusable.It is recommended to use a virtual environment instead: https://pip.pypa.io/warnings/venv. Use the --root-user-action option if you know what you are doing and want to suppress this warning.\u001b[0m\u001b[33m\n",
            "\u001b[0m"
          ]
        }
      ],
      "source": [
        "%pip install --upgrade pip\n",
        "!git clone https://github.com/google-research/bleurt.git\n",
        "!cd bleurt && pip install ."
      ]
    },
    {
      "cell_type": "code",
      "execution_count": 2,
      "metadata": {
        "colab": {
          "base_uri": "https://localhost:8080/"
        },
        "id": "1dj3ZgWvCtAQ",
        "outputId": "d10d018e-d105-4005-ff05-5944413bd9a8"
      },
      "outputs": [
        {
          "name": "stdout",
          "output_type": "stream",
          "text": [
            "2024-09-24 20:26:53.872512: I tensorflow/core/util/port.cc:153] oneDNN custom operations are on. You may see slightly different numerical results due to floating-point round-off errors from different computation orders. To turn them off, set the environment variable `TF_ENABLE_ONEDNN_OPTS=0`.\n",
            "2024-09-24 20:26:53.886542: E external/local_xla/xla/stream_executor/cuda/cuda_fft.cc:485] Unable to register cuFFT factory: Attempting to register factory for plugin cuFFT when one has already been registered\n",
            "2024-09-24 20:26:53.902545: E external/local_xla/xla/stream_executor/cuda/cuda_dnn.cc:8454] Unable to register cuDNN factory: Attempting to register factory for plugin cuDNN when one has already been registered\n",
            "2024-09-24 20:26:53.907323: E external/local_xla/xla/stream_executor/cuda/cuda_blas.cc:1452] Unable to register cuBLAS factory: Attempting to register factory for plugin cuBLAS when one has already been registered\n",
            "2024-09-24 20:26:53.919081: I tensorflow/core/platform/cpu_feature_guard.cc:210] This TensorFlow binary is optimized to use available CPU instructions in performance-critical operations.\n",
            "To enable the following instructions: AVX2 AVX512F AVX512_VNNI FMA, in other operations, rebuild TensorFlow with the appropriate compiler flags.\n",
            "2024-09-24 20:26:54.977931: W tensorflow/compiler/tf2tensorrt/utils/py_utils.cc:38] TF-TRT Warning: Could not find TensorRT\n",
            "2024-09-24 20:26:56.698596: I tensorflow/core/common_runtime/gpu/gpu_device.cc:2021] Created device /job:localhost/replica:0/task:0/device:GPU:0 with 43607 MB memory:  -> device: 0, name: NVIDIA A40, pci bus id: 0000:ce:00.0, compute capability: 8.6\n",
            "..FF.s.F\n",
            "======================================================================\n",
            "FAIL: test_bleurt_score_with_checkpoint (bleurt.score_test.ScoreTest)\n",
            "bleurt.score_test.ScoreTest.test_bleurt_score_with_checkpoint\n",
            "----------------------------------------------------------------------\n",
            "Traceback (most recent call last):\n",
            "  File \"/usr/local/lib/python3.10/dist-packages/bleurt/score_test.py\", line 76, in test_bleurt_score_with_checkpoint\n",
            "    self.assertAllClose(scores, ref_scores)\n",
            "  File \"/usr/local/lib/python3.10/dist-packages/tensorflow/python/framework/test_util.py\", line 1756, in decorated\n",
            "    return f(*args, **kwds)\n",
            "  File \"/usr/local/lib/python3.10/dist-packages/tensorflow/python/framework/test_util.py\", line 3372, in assertAllClose\n",
            "    self._assertAllCloseRecursive(a, b, rtol=rtol, atol=atol, msg=msg)\n",
            "  File \"/usr/local/lib/python3.10/dist-packages/tensorflow/python/framework/test_util.py\", line 3308, in _assertAllCloseRecursive\n",
            "    self._assertArrayLikeAllClose(\n",
            "  File \"/usr/local/lib/python3.10/dist-packages/tensorflow/python/framework/test_util.py\", line 3265, in _assertArrayLikeAllClose\n",
            "    np.testing.assert_allclose(\n",
            "  File \"/usr/local/lib/python3.10/dist-packages/numpy/testing/_private/utils.py\", line 1504, in assert_allclose\n",
            "    assert_array_compare(compare, actual, desired, err_msg=str(err_msg),\n",
            "  File \"/usr/lib/python3.10/contextlib.py\", line 79, in inner\n",
            "    return func(*args, **kwds)\n",
            "  File \"/usr/local/lib/python3.10/dist-packages/numpy/testing/_private/utils.py\", line 797, in assert_array_compare\n",
            "    raise AssertionError(msg)\n",
            "AssertionError: \n",
            "Not equal to tolerance rtol=1e-06, atol=1e-06\n",
            "Mismatched value: a is different from b. \n",
            "not close where = (array([0, 1]),)\n",
            "not close lhs = [0.91081589 0.77200568]\n",
            "not close rhs = [0.910811 0.771989]\n",
            "not close dif = [4.89460373e-06 1.66772232e-05]\n",
            "not close tol = [1.910811e-06 1.771989e-06]\n",
            "dtype = float64, shape = (2,)\n",
            "Mismatched elements: 2 / 2 (100%)\n",
            "Max absolute difference: 1.66772232e-05\n",
            "Max relative difference: 2.16029285e-05\n",
            " x: array([0.910816, 0.772006])\n",
            " y: array([0.910811, 0.771989])\n",
            "\n",
            "======================================================================\n",
            "FAIL: test_default_bleurt_score (bleurt.score_test.ScoreTest)\n",
            "bleurt.score_test.ScoreTest.test_default_bleurt_score\n",
            "----------------------------------------------------------------------\n",
            "Traceback (most recent call last):\n",
            "  File \"/usr/local/lib/python3.10/dist-packages/bleurt/score_test.py\", line 48, in test_default_bleurt_score\n",
            "    self.assertAllClose(scores, ref_scores)\n",
            "  File \"/usr/local/lib/python3.10/dist-packages/tensorflow/python/framework/test_util.py\", line 1756, in decorated\n",
            "    return f(*args, **kwds)\n",
            "  File \"/usr/local/lib/python3.10/dist-packages/tensorflow/python/framework/test_util.py\", line 3372, in assertAllClose\n",
            "    self._assertAllCloseRecursive(a, b, rtol=rtol, atol=atol, msg=msg)\n",
            "  File \"/usr/local/lib/python3.10/dist-packages/tensorflow/python/framework/test_util.py\", line 3308, in _assertAllCloseRecursive\n",
            "    self._assertArrayLikeAllClose(\n",
            "  File \"/usr/local/lib/python3.10/dist-packages/tensorflow/python/framework/test_util.py\", line 3265, in _assertArrayLikeAllClose\n",
            "    np.testing.assert_allclose(\n",
            "  File \"/usr/local/lib/python3.10/dist-packages/numpy/testing/_private/utils.py\", line 1504, in assert_allclose\n",
            "    assert_array_compare(compare, actual, desired, err_msg=str(err_msg),\n",
            "  File \"/usr/lib/python3.10/contextlib.py\", line 79, in inner\n",
            "    return func(*args, **kwds)\n",
            "  File \"/usr/local/lib/python3.10/dist-packages/numpy/testing/_private/utils.py\", line 797, in assert_array_compare\n",
            "    raise AssertionError(msg)\n",
            "AssertionError: \n",
            "Not equal to tolerance rtol=1e-06, atol=1e-06\n",
            "Mismatched value: a is different from b. \n",
            "not close where = (array([0, 1]),)\n",
            "not close lhs = [0.91081589 0.77200568]\n",
            "not close rhs = [0.910811 0.771989]\n",
            "not close dif = [4.89460373e-06 1.66772232e-05]\n",
            "not close tol = [1.910811e-06 1.771989e-06]\n",
            "dtype = float64, shape = (2,)\n",
            "Mismatched elements: 2 / 2 (100%)\n",
            "Max absolute difference: 1.66772232e-05\n",
            "Max relative difference: 2.16029285e-05\n",
            " x: array([0.910816, 0.772006])\n",
            " y: array([0.910811, 0.771989])\n",
            "\n",
            "======================================================================\n",
            "FAIL: test_tf_bleurt_score_eager (bleurt.score_test.ScoreTest)\n",
            "bleurt.score_test.ScoreTest.test_tf_bleurt_score_eager\n",
            "----------------------------------------------------------------------\n",
            "Traceback (most recent call last):\n",
            "  File \"/usr/local/lib/python3.10/dist-packages/bleurt/score_test.py\", line 88, in test_tf_bleurt_score_eager\n",
            "    self.assertAllClose(bleurt_out[\"predictions\"], ref_scores)\n",
            "  File \"/usr/local/lib/python3.10/dist-packages/tensorflow/python/framework/test_util.py\", line 1756, in decorated\n",
            "    return f(*args, **kwds)\n",
            "  File \"/usr/local/lib/python3.10/dist-packages/tensorflow/python/framework/test_util.py\", line 3372, in assertAllClose\n",
            "    self._assertAllCloseRecursive(a, b, rtol=rtol, atol=atol, msg=msg)\n",
            "  File \"/usr/local/lib/python3.10/dist-packages/tensorflow/python/framework/test_util.py\", line 3328, in _assertAllCloseRecursive\n",
            "    self._assertArrayLikeAllClose(\n",
            "  File \"/usr/local/lib/python3.10/dist-packages/tensorflow/python/framework/test_util.py\", line 3265, in _assertArrayLikeAllClose\n",
            "    np.testing.assert_allclose(\n",
            "  File \"/usr/local/lib/python3.10/dist-packages/numpy/testing/_private/utils.py\", line 1504, in assert_allclose\n",
            "    assert_array_compare(compare, actual, desired, err_msg=str(err_msg),\n",
            "  File \"/usr/lib/python3.10/contextlib.py\", line 79, in inner\n",
            "    return func(*args, **kwds)\n",
            "  File \"/usr/local/lib/python3.10/dist-packages/numpy/testing/_private/utils.py\", line 797, in assert_array_compare\n",
            "    raise AssertionError(msg)\n",
            "AssertionError: \n",
            "Not equal to tolerance rtol=1e-06, atol=1e-06\n",
            "Mismatched value: a is different from b. \n",
            "not close where = (array([0, 1]),)\n",
            "not close lhs = [0.9108159 0.7720057]\n",
            "not close rhs = [0.910811 0.771989]\n",
            "not close dif = [4.89460373e-06 1.66772232e-05]\n",
            "not close tol = [1.910811e-06 1.771989e-06]\n",
            "dtype = float32, shape = (2,)\n",
            "Mismatched elements: 2 / 2 (100%)\n",
            "Max absolute difference: 1.66772232e-05\n",
            "Max relative difference: 2.16029285e-05\n",
            " x: array([0.910816, 0.772006], dtype=float32)\n",
            " y: array([0.910811, 0.771989])\n",
            "\n",
            "----------------------------------------------------------------------\n",
            "Ran 8 tests in 5.450s\n",
            "\n",
            "FAILED (failures=3, skipped=1)\n",
            "2024-09-24 20:27:02.772291: I tensorflow/core/util/port.cc:153] oneDNN custom operations are on. You may see slightly different numerical results due to floating-point round-off errors from different computation orders. To turn them off, set the environment variable `TF_ENABLE_ONEDNN_OPTS=0`.\n",
            "2024-09-24 20:27:02.786078: E external/local_xla/xla/stream_executor/cuda/cuda_fft.cc:485] Unable to register cuFFT factory: Attempting to register factory for plugin cuFFT when one has already been registered\n",
            "2024-09-24 20:27:02.802164: E external/local_xla/xla/stream_executor/cuda/cuda_dnn.cc:8454] Unable to register cuDNN factory: Attempting to register factory for plugin cuDNN when one has already been registered\n",
            "2024-09-24 20:27:02.806977: E external/local_xla/xla/stream_executor/cuda/cuda_blas.cc:1452] Unable to register cuBLAS factory: Attempting to register factory for plugin cuBLAS when one has already been registered\n",
            "2024-09-24 20:27:02.818803: I tensorflow/core/platform/cpu_feature_guard.cc:210] This TensorFlow binary is optimized to use available CPU instructions in performance-critical operations.\n",
            "To enable the following instructions: AVX2 AVX512F AVX512_VNNI FMA, in other operations, rebuild TensorFlow with the appropriate compiler flags.\n",
            "2024-09-24 20:27:03.839478: W tensorflow/compiler/tf2tensorrt/utils/py_utils.cc:38] TF-TRT Warning: Could not find TensorRT\n",
            "WARNING:tensorflow:Using Tensorflow Sessions---please call `.close()` when you are are done using the BleurtScorer.\n",
            "2024-09-24 20:27:05.380075: I tensorflow/core/common_runtime/gpu/gpu_device.cc:2021] Created device /job:localhost/replica:0/task:0/device:GPU:0 with 43607 MB memory:  -> device: 0, name: NVIDIA A40, pci bus id: 0000:ce:00.0, compute capability: 8.6\n",
            "2024-09-24 20:27:05.584007: I tensorflow/core/common_runtime/gpu/gpu_device.cc:2021] Created device /job:localhost/replica:0/task:0/device:GPU:0 with 43607 MB memory:  -> device: 0, name: NVIDIA A40, pci bus id: 0000:ce:00.0, compute capability: 8.6\n",
            "2024-09-24 20:27:05.603002: I tensorflow/compiler/mlir/mlir_graph_optimization_pass.cc:388] MLIR V1 optimization pass is not enabled\n",
            "Fs2024-09-24 20:27:07.612908: I tensorflow/core/common_runtime/gpu/gpu_device.cc:2021] Created device /job:localhost/replica:0/task:0/device:GPU:0 with 43607 MB memory:  -> device: 0, name: NVIDIA A40, pci bus id: 0000:ce:00.0, compute capability: 8.6\n",
            "F\n",
            "======================================================================\n",
            "FAIL: test_default_bleurt_score (bleurt.score_not_eager_test.ScoreTest)\n",
            "bleurt.score_not_eager_test.ScoreTest.test_default_bleurt_score\n",
            "----------------------------------------------------------------------\n",
            "Traceback (most recent call last):\n",
            "  File \"/usr/local/lib/python3.10/dist-packages/bleurt/score_not_eager_test.py\", line 49, in test_default_bleurt_score\n",
            "    self.assertAllClose(scores, ref_scores)\n",
            "  File \"/usr/local/lib/python3.10/dist-packages/tensorflow/python/framework/test_util.py\", line 1756, in decorated\n",
            "    return f(*args, **kwds)\n",
            "  File \"/usr/local/lib/python3.10/dist-packages/tensorflow/python/framework/test_util.py\", line 3372, in assertAllClose\n",
            "    self._assertAllCloseRecursive(a, b, rtol=rtol, atol=atol, msg=msg)\n",
            "  File \"/usr/local/lib/python3.10/dist-packages/tensorflow/python/framework/test_util.py\", line 3308, in _assertAllCloseRecursive\n",
            "    self._assertArrayLikeAllClose(\n",
            "  File \"/usr/local/lib/python3.10/dist-packages/tensorflow/python/framework/test_util.py\", line 3265, in _assertArrayLikeAllClose\n",
            "    np.testing.assert_allclose(\n",
            "  File \"/usr/local/lib/python3.10/dist-packages/numpy/testing/_private/utils.py\", line 1504, in assert_allclose\n",
            "    assert_array_compare(compare, actual, desired, err_msg=str(err_msg),\n",
            "  File \"/usr/lib/python3.10/contextlib.py\", line 79, in inner\n",
            "    return func(*args, **kwds)\n",
            "  File \"/usr/local/lib/python3.10/dist-packages/numpy/testing/_private/utils.py\", line 797, in assert_array_compare\n",
            "    raise AssertionError(msg)\n",
            "AssertionError: \n",
            "Not equal to tolerance rtol=1e-06, atol=1e-06\n",
            "Mismatched value: a is different from b. \n",
            "not close where = (array([0, 1]),)\n",
            "not close lhs = [0.91081595 0.77200556]\n",
            "not close rhs = [0.910811 0.771989]\n",
            "not close dif = [4.95420837e-06 1.65580139e-05]\n",
            "not close tol = [1.910811e-06 1.771989e-06]\n",
            "dtype = float64, shape = (2,)\n",
            "Mismatched elements: 2 / 2 (100%)\n",
            "Max absolute difference: 1.65580139e-05\n",
            "Max relative difference: 2.14485102e-05\n",
            " x: array([0.910816, 0.772006])\n",
            " y: array([0.910811, 0.771989])\n",
            "\n",
            "======================================================================\n",
            "FAIL: test_tf_bleurt_score_not_eager (bleurt.score_not_eager_test.ScoreTest)\n",
            "bleurt.score_not_eager_test.ScoreTest.test_tf_bleurt_score_not_eager\n",
            "----------------------------------------------------------------------\n",
            "Traceback (most recent call last):\n",
            "  File \"/usr/local/lib/python3.10/dist-packages/bleurt/score_not_eager_test.py\", line 67, in test_tf_bleurt_score_not_eager\n",
            "    self.assertAllClose(bleurt_out[\"predictions\"], ref_scores)\n",
            "  File \"/usr/local/lib/python3.10/dist-packages/tensorflow/python/framework/test_util.py\", line 1756, in decorated\n",
            "    return f(*args, **kwds)\n",
            "  File \"/usr/local/lib/python3.10/dist-packages/tensorflow/python/framework/test_util.py\", line 3372, in assertAllClose\n",
            "    self._assertAllCloseRecursive(a, b, rtol=rtol, atol=atol, msg=msg)\n",
            "  File \"/usr/local/lib/python3.10/dist-packages/tensorflow/python/framework/test_util.py\", line 3328, in _assertAllCloseRecursive\n",
            "    self._assertArrayLikeAllClose(\n",
            "  File \"/usr/local/lib/python3.10/dist-packages/tensorflow/python/framework/test_util.py\", line 3265, in _assertArrayLikeAllClose\n",
            "    np.testing.assert_allclose(\n",
            "  File \"/usr/local/lib/python3.10/dist-packages/numpy/testing/_private/utils.py\", line 1504, in assert_allclose\n",
            "    assert_array_compare(compare, actual, desired, err_msg=str(err_msg),\n",
            "  File \"/usr/lib/python3.10/contextlib.py\", line 79, in inner\n",
            "    return func(*args, **kwds)\n",
            "  File \"/usr/local/lib/python3.10/dist-packages/numpy/testing/_private/utils.py\", line 797, in assert_array_compare\n",
            "    raise AssertionError(msg)\n",
            "AssertionError: \n",
            "Not equal to tolerance rtol=1e-06, atol=1e-06\n",
            "Mismatched value: a is different from b. \n",
            "not close where = (array([0, 1]),)\n",
            "not close lhs = [0.91081595 0.77200556]\n",
            "not close rhs = [0.910811 0.771989]\n",
            "not close dif = [4.95420837e-06 1.65580139e-05]\n",
            "not close tol = [1.910811e-06 1.771989e-06]\n",
            "dtype = float32, shape = (2,)\n",
            "Mismatched elements: 2 / 2 (100%)\n",
            "Max absolute difference: 1.65580139e-05\n",
            "Max relative difference: 2.14485102e-05\n",
            " x: array([0.910816, 0.772006], dtype=float32)\n",
            " y: array([0.910811, 0.771989])\n",
            "\n",
            "----------------------------------------------------------------------\n",
            "Ran 3 tests in 4.376s\n",
            "\n",
            "FAILED (failures=2, skipped=1)\n",
            "2024-09-24 20:27:10.437239: I tensorflow/core/util/port.cc:153] oneDNN custom operations are on. You may see slightly different numerical results due to floating-point round-off errors from different computation orders. To turn them off, set the environment variable `TF_ENABLE_ONEDNN_OPTS=0`.\n",
            "2024-09-24 20:27:10.450961: E external/local_xla/xla/stream_executor/cuda/cuda_fft.cc:485] Unable to register cuFFT factory: Attempting to register factory for plugin cuFFT when one has already been registered\n",
            "2024-09-24 20:27:10.467163: E external/local_xla/xla/stream_executor/cuda/cuda_dnn.cc:8454] Unable to register cuDNN factory: Attempting to register factory for plugin cuDNN when one has already been registered\n",
            "2024-09-24 20:27:10.471986: E external/local_xla/xla/stream_executor/cuda/cuda_blas.cc:1452] Unable to register cuBLAS factory: Attempting to register factory for plugin cuBLAS when one has already been registered\n",
            "2024-09-24 20:27:10.483852: I tensorflow/core/platform/cpu_feature_guard.cc:210] This TensorFlow binary is optimized to use available CPU instructions in performance-critical operations.\n",
            "To enable the following instructions: AVX2 AVX512F AVX512_VNNI FMA, in other operations, rebuild TensorFlow with the appropriate compiler flags.\n",
            "2024-09-24 20:27:11.530057: W tensorflow/compiler/tf2tensorrt/utils/py_utils.cc:38] TF-TRT Warning: Could not find TensorRT\n",
            "E\n",
            "======================================================================\n",
            "ERROR: finetune_test (unittest.loader._FailedTest)\n",
            "----------------------------------------------------------------------\n",
            "ImportError: Failed to import test module: finetune_test\n",
            "Traceback (most recent call last):\n",
            "  File \"/usr/lib/python3.10/unittest/loader.py\", line 154, in loadTestsFromName\n",
            "    module = __import__(module_name)\n",
            "  File \"/usr/local/lib/python3.10/dist-packages/bleurt/finetune_test.py\", line 20, in <module>\n",
            "    from bleurt import finetune\n",
            "  File \"/usr/local/lib/python3.10/dist-packages/bleurt/finetune.py\", line 20, in <module>\n",
            "    from bleurt import model\n",
            "  File \"/usr/local/lib/python3.10/dist-packages/bleurt/model.py\", line 23, in <module>\n",
            "    from tensorflow.compat.v1 import estimator as tf_estimator\n",
            "ImportError: cannot import name 'estimator' from 'tensorflow.compat.v1' (/usr/local/lib/python3.10/dist-packages/tensorflow/_api/v2/compat/v1/__init__.py)\n",
            "\n",
            "\n",
            "----------------------------------------------------------------------\n",
            "Ran 1 test in 0.000s\n",
            "\n",
            "FAILED (errors=1)\n",
            "2024-09-24 20:27:13.705614: I tensorflow/core/util/port.cc:153] oneDNN custom operations are on. You may see slightly different numerical results due to floating-point round-off errors from different computation orders. To turn them off, set the environment variable `TF_ENABLE_ONEDNN_OPTS=0`.\n",
            "2024-09-24 20:27:13.719309: E external/local_xla/xla/stream_executor/cuda/cuda_fft.cc:485] Unable to register cuFFT factory: Attempting to register factory for plugin cuFFT when one has already been registered\n",
            "2024-09-24 20:27:13.735427: E external/local_xla/xla/stream_executor/cuda/cuda_dnn.cc:8454] Unable to register cuDNN factory: Attempting to register factory for plugin cuDNN when one has already been registered\n",
            "2024-09-24 20:27:13.740224: E external/local_xla/xla/stream_executor/cuda/cuda_blas.cc:1452] Unable to register cuBLAS factory: Attempting to register factory for plugin cuBLAS when one has already been registered\n",
            "2024-09-24 20:27:13.751990: I tensorflow/core/platform/cpu_feature_guard.cc:210] This TensorFlow binary is optimized to use available CPU instructions in performance-critical operations.\n",
            "To enable the following instructions: AVX2 AVX512F AVX512_VNNI FMA, in other operations, rebuild TensorFlow with the appropriate compiler flags.\n",
            "2024-09-24 20:27:14.837918: W tensorflow/compiler/tf2tensorrt/utils/py_utils.cc:38] TF-TRT Warning: Could not find TensorRT\n",
            "2024-09-24 20:27:16.336341: I tensorflow/core/common_runtime/gpu/gpu_device.cc:2021] Created device /job:localhost/replica:0/task:0/device:GPU:0 with 43607 MB memory:  -> device: 0, name: NVIDIA A40, pci bus id: 0000:ce:00.0, compute capability: 8.6\n",
            "...FFFFFsF.\n",
            "======================================================================\n",
            "FAIL: test_score_empty_candidate_and_reference_text (bleurt.score_files_test.ScoreFilesTest)\n",
            "bleurt.score_files_test.ScoreFilesTest.test_score_empty_candidate_and_reference_text\n",
            "----------------------------------------------------------------------\n",
            "Traceback (most recent call last):\n",
            "  File \"/usr/local/lib/python3.10/dist-packages/bleurt/score_files_test.py\", line 187, in test_score_empty_candidate_and_reference_text\n",
            "    self.assertAllClose(scores, [0.679957])\n",
            "  File \"/usr/local/lib/python3.10/dist-packages/tensorflow/python/framework/test_util.py\", line 1756, in decorated\n",
            "    return f(*args, **kwds)\n",
            "  File \"/usr/local/lib/python3.10/dist-packages/tensorflow/python/framework/test_util.py\", line 3372, in assertAllClose\n",
            "    self._assertAllCloseRecursive(a, b, rtol=rtol, atol=atol, msg=msg)\n",
            "  File \"/usr/local/lib/python3.10/dist-packages/tensorflow/python/framework/test_util.py\", line 3308, in _assertAllCloseRecursive\n",
            "    self._assertArrayLikeAllClose(\n",
            "  File \"/usr/local/lib/python3.10/dist-packages/tensorflow/python/framework/test_util.py\", line 3265, in _assertArrayLikeAllClose\n",
            "    np.testing.assert_allclose(\n",
            "  File \"/usr/local/lib/python3.10/dist-packages/numpy/testing/_private/utils.py\", line 1504, in assert_allclose\n",
            "    assert_array_compare(compare, actual, desired, err_msg=str(err_msg),\n",
            "  File \"/usr/lib/python3.10/contextlib.py\", line 79, in inner\n",
            "    return func(*args, **kwds)\n",
            "  File \"/usr/local/lib/python3.10/dist-packages/numpy/testing/_private/utils.py\", line 797, in assert_array_compare\n",
            "    raise AssertionError(msg)\n",
            "AssertionError: \n",
            "Not equal to tolerance rtol=1e-06, atol=1e-06\n",
            "Mismatched value: a is different from b. \n",
            "not close where = (array([0]),)\n",
            "not close lhs = [0.68007308]\n",
            "not close rhs = [0.679957]\n",
            "not close dif = [0.00011608]\n",
            "not close tol = [1.679957e-06]\n",
            "dtype = float64, shape = (1,)\n",
            "Mismatched elements: 1 / 1 (100%)\n",
            "Max absolute difference: 0.00011608\n",
            "Max relative difference: 0.00017072\n",
            " x: array([0.680073])\n",
            " y: array([0.679957])\n",
            "\n",
            "======================================================================\n",
            "FAIL: test_score_empty_reference_and_candidate_pair (bleurt.score_files_test.ScoreFilesTest)\n",
            "bleurt.score_files_test.ScoreFilesTest.test_score_empty_reference_and_candidate_pair\n",
            "----------------------------------------------------------------------\n",
            "Traceback (most recent call last):\n",
            "  File \"/usr/local/lib/python3.10/dist-packages/bleurt/score_files_test.py\", line 201, in test_score_empty_reference_and_candidate_pair\n",
            "    self.assertAllClose(scores, [0.679957])\n",
            "  File \"/usr/local/lib/python3.10/dist-packages/tensorflow/python/framework/test_util.py\", line 1756, in decorated\n",
            "    return f(*args, **kwds)\n",
            "  File \"/usr/local/lib/python3.10/dist-packages/tensorflow/python/framework/test_util.py\", line 3372, in assertAllClose\n",
            "    self._assertAllCloseRecursive(a, b, rtol=rtol, atol=atol, msg=msg)\n",
            "  File \"/usr/local/lib/python3.10/dist-packages/tensorflow/python/framework/test_util.py\", line 3308, in _assertAllCloseRecursive\n",
            "    self._assertArrayLikeAllClose(\n",
            "  File \"/usr/local/lib/python3.10/dist-packages/tensorflow/python/framework/test_util.py\", line 3265, in _assertArrayLikeAllClose\n",
            "    np.testing.assert_allclose(\n",
            "  File \"/usr/local/lib/python3.10/dist-packages/numpy/testing/_private/utils.py\", line 1504, in assert_allclose\n",
            "    assert_array_compare(compare, actual, desired, err_msg=str(err_msg),\n",
            "  File \"/usr/lib/python3.10/contextlib.py\", line 79, in inner\n",
            "    return func(*args, **kwds)\n",
            "  File \"/usr/local/lib/python3.10/dist-packages/numpy/testing/_private/utils.py\", line 797, in assert_array_compare\n",
            "    raise AssertionError(msg)\n",
            "AssertionError: \n",
            "Not equal to tolerance rtol=1e-06, atol=1e-06\n",
            "Mismatched value: a is different from b. \n",
            "not close where = (array([0]),)\n",
            "not close lhs = [0.68007308]\n",
            "not close rhs = [0.679957]\n",
            "not close dif = [0.00011608]\n",
            "not close tol = [1.679957e-06]\n",
            "dtype = float64, shape = (1,)\n",
            "Mismatched elements: 1 / 1 (100%)\n",
            "Max absolute difference: 0.00011608\n",
            "Max relative difference: 0.00017072\n",
            " x: array([0.680073])\n",
            " y: array([0.679957])\n",
            "\n",
            "======================================================================\n",
            "FAIL: test_score_files_sentence_pairs (bleurt.score_files_test.ScoreFilesTest)\n",
            "bleurt.score_files_test.ScoreFilesTest.test_score_files_sentence_pairs\n",
            "----------------------------------------------------------------------\n",
            "Traceback (most recent call last):\n",
            "  File \"/usr/local/lib/python3.10/dist-packages/bleurt/score_files_test.py\", line 91, in test_score_files_sentence_pairs\n",
            "    sentence_pairs_file, _, _ = get_test_data()\n",
            "  File \"/usr/local/lib/python3.10/dist-packages/bleurt/score_files_test.py\", line 43, in get_test_data\n",
            "    assert tf.io.gfile.exists(sentence_pairs_file)\n",
            "AssertionError\n",
            "\n",
            "======================================================================\n",
            "FAIL: test_score_files_text (bleurt.score_files_test.ScoreFilesTest)\n",
            "bleurt.score_files_test.ScoreFilesTest.test_score_files_text\n",
            "----------------------------------------------------------------------\n",
            "Traceback (most recent call last):\n",
            "  File \"/usr/local/lib/python3.10/dist-packages/bleurt/score_files_test.py\", line 105, in test_score_files_text\n",
            "    _, reference_file, candidate_file = get_test_data()\n",
            "  File \"/usr/local/lib/python3.10/dist-packages/bleurt/score_files_test.py\", line 43, in get_test_data\n",
            "    assert tf.io.gfile.exists(sentence_pairs_file)\n",
            "AssertionError\n",
            "\n",
            "======================================================================\n",
            "FAIL: test_sentence_pairs_consume_buffer (bleurt.score_files_test.ScoreFilesTest)\n",
            "bleurt.score_files_test.ScoreFilesTest.test_sentence_pairs_consume_buffer\n",
            "----------------------------------------------------------------------\n",
            "Traceback (most recent call last):\n",
            "  File \"/usr/local/lib/python3.10/dist-packages/bleurt/score_files_test.py\", line 147, in test_sentence_pairs_consume_buffer\n",
            "    sentence_pairs_file, _, _ = get_test_data()\n",
            "  File \"/usr/local/lib/python3.10/dist-packages/bleurt/score_files_test.py\", line 43, in get_test_data\n",
            "    assert tf.io.gfile.exists(sentence_pairs_file)\n",
            "AssertionError\n",
            "\n",
            "======================================================================\n",
            "FAIL: test_text_consume_buffer (bleurt.score_files_test.ScoreFilesTest)\n",
            "bleurt.score_files_test.ScoreFilesTest.test_text_consume_buffer\n",
            "----------------------------------------------------------------------\n",
            "Traceback (most recent call last):\n",
            "  File \"/usr/local/lib/python3.10/dist-packages/bleurt/score_files_test.py\", line 161, in test_text_consume_buffer\n",
            "    _, reference_file, candidate_file = get_test_data()\n",
            "  File \"/usr/local/lib/python3.10/dist-packages/bleurt/score_files_test.py\", line 43, in get_test_data\n",
            "    assert tf.io.gfile.exists(sentence_pairs_file)\n",
            "AssertionError\n",
            "\n",
            "----------------------------------------------------------------------\n",
            "Ran 11 tests in 5.039s\n",
            "\n",
            "FAILED (failures=6, skipped=1)\n"
          ]
        }
      ],
      "source": [
        "!python -m unittest bleurt.score_test\n",
        "!python -m unittest bleurt.score_not_eager_test\n",
        "!python -m unittest bleurt.finetune_test\n",
        "!python -m unittest bleurt.score_files_test"
      ]
    }
  ],
  "metadata": {
    "accelerator": "TPU",
    "colab": {
      "gpuType": "V28",
      "provenance": []
    },
    "kernelspec": {
      "display_name": "Python 3",
      "language": "python",
      "name": "python3"
    },
    "language_info": {
      "codemirror_mode": {
        "name": "ipython",
        "version": 3
      },
      "file_extension": ".py",
      "mimetype": "text/x-python",
      "name": "python",
      "nbconvert_exporter": "python",
      "pygments_lexer": "ipython3",
      "version": "3.9.6"
    }
  },
  "nbformat": 4,
  "nbformat_minor": 0
}
